FROM alpine:latest AS builder

ARG VERSION=2.28.0

RUN apk --update add wget; \
    wget -qO- https://github.com/xiaokaixuan/filebrowser/releases/download/v${VERSION}/linux-arm64-filebrowser.tar.gz | tar zx -C / filebrowser; \
    chmod a+x filebrowser
    
FROM scratch

VOLUME /srv
EXPOSE 80

COPY .docker.json /.filebrowser.json
COPY --from=builder /filebrowser /filebrowser

ENTRYPOINT ["/filebrowser", "-c", "/.filebrowser.json"]

